name: Bug Report
description: Report a bug
title: "[BUG] - "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Provide a detailed description of the bug you encountered here
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug in detail, including steps to reproduce it.
      placeholder: "By example: Something is missing, command is not working when it should, etc."
  - type: input
    id: what-is-happening
    attributes:
      label: what-is-happening
      placeholder: "What is happening?"
      validations:
        required: true
