name: Feature Request
description: Suggest a feature
title: "[Feature Request] "
labels: ["request"]
body:
  - type: markdown
    attributes:
      value: |
        Give details on your feature request below

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A detailed description of the feature you are requesting.
      placeholder: "Anything about the feature that you are requesting!"
      validations:
        required: true