name: Feature Request
description: Suggest a feature
title: "[Feature Request] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Describe what do you want to add
  - type: textarea
    id: solution
    attributes:
      label: What do you want to add?
      description: Describe how the feature would work
      placeholder: "A description of the feature you want to add."
    validations:
      required: true